# Generated by Django 4.2.6 on 2023-10-18 18:23
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, height_field=models.PositiveIntegerField(), upload_to='media/', width_field=models.PositiveIntegerField())),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='posters.tag')),
            ],
            options={
                'ordering': ('-date_add',),
            },
        ),
    ]
