# Generated by Django 4.2.6 on 2023-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_tag_date_add_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(), upload_to='media', width_field=models.PositiveIntegerField()),
        ),
    ]
